### PR TITLE
Main page/am

### PR DESCRIPTION
**Pull request by Andrew-Musselman**
We have some functionality for iteration 0. Still need to work on event listener for randomize button.

### CODE REVIEW

**Comment by kmewrd** [comment]
I added a few lines to make the randomize button functional. I also fixed an issue with the 'click' event listener - we had getNewRandomPoster as the function, even though we deleted that function before committing and pushing changes. (You won't see it anywhere in our commits.)

Take a look and let me know what you think. I'll merge changes once you've seen my new commit. I don't think they want the person who opened the pull request to merge it.

**Comment by kmewrd** [comment]
I just fixed the 'load' event listener and refactored so the currentPoster var is back above our functions. I think this is how they wanted us to lay out the main.js file. Let me know if it looks good to merge.

**Review by Andrew-Musselman — COMMENTED** [review]
This looks really good! And everything makes sense. I think this is ready to merge!

**Comment by Andrew-Musselman** [comment]
Merged on call live with @kmewrd

**Pull request merged**
